[package]
name        = "ailake-cache"
version     = "0.1.14"
edition     = "2021"
description = "Local and Redis/Valkey cache for AI-Lake metadata, queries and index reads"
license     = "MIT OR Apache-2.0"
repository  = "https://github.com/ThiagoLange/ai-lakehouse"

[features]
default = []
redis = ["dep:redis"]

[dependencies]
ailake-core  = { path = "../ailake-core", version = "0.1.14" }
ailake-store = { path = "../ailake-store", version = "0.1.14" }
async-trait  = { workspace = true }
bytes        = { workspace = true }
redis        = { workspace = true, optional = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }

[dev-dependencies]
tempfile     = { workspace = true }
